### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dxl3742** [kad-ecoli/hhsuite2#3]
Hi Kad,
I'm trying to install the hhsuite2, except I don't have sudo or root access so I can't get the static binaries. I have tried make all, but I get errors like this:
<img width="620" alt="image" src="https://github.com/kad-ecoli/hhsuite2/assets/94665211/5df76ab4-918f-4e3f-b0f6-ade27a8ab120">
<img width="602" alt="image" src="https://github.com/kad-ecoli/hhsuite2/assets/94665211/009d92ce-89c4-4ae1-a6b9-5ccbaae59d72">
Any help would be greatly appreciated, thanks in advance!

**Comment by kad-ecoli** [comment]
You do NOT need sudo or root to use static binary. Please try to use the precompiled version first.
